# Generated by Django 6.0.2 on 2026-03-06 10:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='business',
            field=models.ForeignKey(help_text='The business this client belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.businessprofile'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('walkin', 'Walk-in'), ('regular', 'Regular'), ('corporate', 'Corporate')], default='walkin', help_text='Type of client relationship', max_length=20, verbose_name='Client Type'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the client record was created', verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(help_text="Client's complete name", max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the client', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount client still owes (auto-calculated)', max_digits=10, verbose_name='Outstanding Balance'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(help_text="Client's contact phone number", max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='total_spending',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount spent by client (auto-calculated)', max_digits=10, verbose_name='Total Spending'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('business', 'full_name')},
        ),
    ]
