# Generated by Codex on 2026-03-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_business_owners(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    BusinessProfile = apps.get_model('core', 'BusinessProfile')

    def get_display_name(user):
        first_name = (getattr(user, 'first_name', '') or '').strip()
        last_name = (getattr(user, 'last_name', '') or '').strip()
        full_name = f"{first_name} {last_name}".strip()
        return full_name or user.username

    unowned_businesses = list(BusinessProfile.objects.filter(owner__isnull=True).order_by('id'))

    for user in User.objects.order_by('id'):
        if BusinessProfile.objects.filter(owner=user).exists():
            continue

        if unowned_businesses:
            business = unowned_businesses.pop(0)
            business.owner = user
            if not business.owner_name:
                business.owner_name = get_display_name(user)
            if not business.email:
                business.email = user.email or ''
            business.save(update_fields=['owner', 'owner_name', 'email'])
            continue

        display_name = get_display_name(user)
        BusinessProfile.objects.create(
            owner=user,
            name=f"{display_name}'s Cyber Cafe",
            owner_name=display_name,
            phone='',
            email=user.email or '',
            location='',
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_businessprofile_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(assign_business_owners, noop_reverse),
    ]
