# Generated by Codex on 2026-03-21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    BusinessProfile = apps.get_model('core', 'BusinessProfile')
    UserProfile = apps.get_model('core', 'UserProfile')

    for user in User.objects.order_by('id'):
        profile_exists = UserProfile.objects.filter(user=user).exists()
        if profile_exists:
            continue

        business = BusinessProfile.objects.filter(owner=user).first()
        if business is None:
            display_name = ' '.join(
                part for part in [getattr(user, 'first_name', ''), getattr(user, 'last_name', '')] if part
            ).strip() or user.username
            business = BusinessProfile.objects.create(
                owner=user,
                name=f"{display_name}'s Cyber Cafe",
                owner_name=display_name,
                phone='',
                email=user.email or '',
                location='',
            )

        UserProfile.objects.create(
            user=user,
            business=business,
            role='admin',
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_businessprofile_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('create', 'Create Record'), ('update', 'Update Record'), ('delete', 'Delete Record'), ('view', 'View Record'), ('export', 'Export Data'), ('backup', 'Database Backup'), ('restore', 'Database Restore'), ('failed_login', 'Failed Login Attempt')], max_length=20)),
                ('description', models.TextField(help_text='Description of the activity')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                ('related_object_type', models.CharField(blank=True, help_text="Type of related object (e.g., 'Client', 'Transaction')", max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.businessprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(fields=['user', 'timestamp'], name='core_activi_user_id_a5e86b_idx'),
                    models.Index(fields=['action', 'timestamp'], name='core_activi_action_baa1e8_idx'),
                    models.Index(fields=['business', 'timestamp'], name='core_activi_busines_9c83c6_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60, help_text='Session timeout in minutes')),
                ('max_login_attempts', models.PositiveIntegerField(default=5, help_text='Maximum login attempts before lockout')),
                ('lockout_duration_minutes', models.PositiveIntegerField(default=30, help_text='Account lockout duration in minutes')),
                ('auto_backup_enabled', models.BooleanField(default=True, help_text='Enable automatic daily backups')),
                ('backup_retention_days', models.PositiveIntegerField(default=30, help_text='Number of days to keep backups')),
                ('currency_symbol', models.CharField(default='KSh', help_text='Currency symbol for display', max_length=10)),
                ('date_format', models.CharField(default='Y-m-d', help_text='Date format for display', max_length=20)),
                ('timezone', models.CharField(default='UTC', help_text='System timezone', max_length=50)),
                ('email_notifications_enabled', models.BooleanField(default=False, help_text='Enable email notifications')),
                ('smtp_server', models.CharField(blank=True, help_text='SMTP server address', max_length=100)),
                ('smtp_port', models.PositiveIntegerField(default=587, help_text='SMTP server port')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_settings', to='core.businessprofile')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', help_text="User's role in the system", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('login_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('password_changed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('require_password_change', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='Business this user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='core.businessprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'unique_together': {('user', 'business')},
            },
        ),
        migrations.RunPython(create_profiles_for_existing_users, noop_reverse),
    ]
