# Generated by Codex on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_security_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Supplier Name'),
        ),
    ]
