# Generated by Codex on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_expense_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='supplier_contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Supplier Contact'),
        ),
    ]
