# Generated by Codex on 2026-03-24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def move_existing_supply_expenses(apps, schema_editor):
    Expense = apps.get_model('core', 'Expense')
    SupplyExpense = apps.get_model('core', 'SupplyExpense')

    supply_rows = Expense.objects.filter(category='supplies')
    for row in supply_rows.iterator():
        SupplyExpense.objects.create(
            business=row.business,
            date=row.date,
            supplier_name=row.supplier_name or 'Unknown supplier',
            supplier_contact=row.supplier_contact or '',
            description=row.description,
            amount=row.amount,
        )

    supply_rows.delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_expense_supplier_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='Supplier Name')),
                ('supplier_contact', models.CharField(blank=True, max_length=255, verbose_name='Supplier Contact')),
                ('description', models.TextField(blank=True, verbose_name='Supplies Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_expenses', to='core.businessprofile')),
            ],
            options={
                'verbose_name': 'Supply Expense',
                'verbose_name_plural': 'Supply Expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.RunPython(move_existing_supply_expenses, noop_reverse),
    ]
