# Generated by Django 6.0.2 on 2026-03-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_supplyexpense_payables'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_user_id_81b1f1_idx',
            old_name='core_activi_user_id_a5e86b_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_action_549521_idx',
            old_name='core_activi_action_baa1e8_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_busines_2d5c18_idx',
            old_name='core_activi_busines_9c83c6_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Client's contact phone number", max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='supplyexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount'),
        ),
    ]
