from django.urls import path
from . import views
from .reporting import (
    ReportIndexView, DailyReportView, MonthlyReportView,
    YearlyReportView, CustomReportView, BackupView, RestoreView,
    export_daily_report_pdf, export_monthly_report_pdf,
    export_yearly_report_pdf, export_custom_report_pdf
)

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('business/', views.BusinessListView.as_view(), name='business_list'),
    path('business/add/', views.BusinessCreateView.as_view(), name='business_add'),
    path('business/<int:pk>/edit/', views.BusinessUpdateView.as_view(), name='business_edit'),
    path('business/<int:pk>/delete/', views.BusinessDeleteView.as_view(), name='business_delete'),
    path('clients/', views.ClientListView.as_view(), name='client_list'),
    path('clients/add/', views.ClientCreateView.as_view(), name='client_add'),
    path('clients/<int:pk>/edit/', views.ClientUpdateView.as_view(), name='client_edit'),
    path('clients/<int:pk>/delete/', views.ClientDeleteView.as_view(), name='client_delete'),
    path('transactions/', views.TransactionListView.as_view(), name='transaction_list'),
    path('transactions/add/', views.TransactionCreateView.as_view(), name='transaction_add'),
    path('transactions/<int:pk>/edit/', views.TransactionUpdateView.as_view(), name='transaction_edit'),
    path('transactions/<int:pk>/delete/', views.TransactionDeleteView.as_view(), name='transaction_delete'),
    path('expenses/', views.ExpenseListView.as_view(), name='expense_list'),
    path('expenses/add/', views.ExpenseCreateView.as_view(), name='expense_add'),
    path('expenses/<int:pk>/edit/', views.ExpenseUpdateView.as_view(), name='expense_edit'),
    path('expenses/<int:pk>/delete/', views.ExpenseDeleteView.as_view(), name='expense_delete'),
    path('supply-expenses/', views.SupplyExpenseListView.as_view(), name='supply_expense_list'),
    path('supply-expenses/add/', views.SupplyExpenseCreateView.as_view(), name='supply_expense_add'),
    path('supply-expenses/<int:pk>/edit/', views.SupplyExpenseUpdateView.as_view(), name='supply_expense_edit'),
    path('supply-expenses/<int:pk>/delete/', views.SupplyExpenseDeleteView.as_view(), name='supply_expense_delete'),
    # reporting and backup
    path('reports/', ReportIndexView.as_view(), name='report_index'),
    path('reports/daily/', DailyReportView.as_view(), name='daily_report'),
    path('reports/monthly/', MonthlyReportView.as_view(), name='monthly_report'),
    path('reports/yearly/', YearlyReportView.as_view(), name='yearly_report'),
    path('reports/custom/', CustomReportView.as_view(), name='custom_report'),
    path('net-profit/', views.net_profit_detail, name='net_profit_detail'),
    path('daily-revenue-detail/', views.DailyRevenueDetailView.as_view(), name='daily_revenue_detail'),
    path('outstanding-balances/', views.OutstandingBalanceListView.as_view(), name='outstanding_balances'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('team/', views.TeamManagementView.as_view(), name='team_management'),
    path('team/<int:pk>/edit/', views.TeamMemberUpdateView.as_view(), name='team_member_edit'),
    path('backup/', BackupView.as_view(), name='backup'),
    path('backup/download/', views.backup, name='backup_download'),
    path('restore/', RestoreView.as_view(), name='restore'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    # export functions
    path('export/daily/pdf/', export_daily_report_pdf, name='export_daily_report_pdf'),
    path('export/monthly/pdf/', export_monthly_report_pdf, name='export_monthly_report_pdf'),
    path('export/yearly/pdf/', export_yearly_report_pdf, name='export_yearly_report_pdf'),
    path('export/custom/pdf/', export_custom_report_pdf, name='export_custom_report_pdf'),
    # authentication
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.LogoutView, name='logout'),
]
