from django.urls import path
from . import views
from . import super_admin
from .reporting import (
    ReportIndexView, DailyReportView, MonthlyReportView,
    YearlyReportView, CustomReportView, BackupView, RestoreView,
    export_daily_report_pdf, export_monthly_report_pdf,
    export_yearly_report_pdf, export_custom_report_pdf
)

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('super-admin/', super_admin.SuperAdminDashboardView.as_view(), name='super_admin_home'),
    path('super-admin/dashboard/', super_admin.SuperAdminDashboardView.as_view(), name='super_admin_dashboard'),
    path('super-admin/revenue/', super_admin.SuperAdminRevenueBreakdownView.as_view(), name='super_admin_revenue_breakdown'),
    path('super-admin/clients/', super_admin.SuperAdminClientListView.as_view(), name='super_admin_client_list'),
    path('super-admin/clients/add/', super_admin.SuperAdminClientCreateView.as_view(), name='super_admin_client_add'),
    path('super-admin/clients/<int:pk>/', super_admin.SuperAdminClientDetailView.as_view(), name='super_admin_client_detail'),
    path('super-admin/clients/<int:pk>/edit/', super_admin.SuperAdminClientUpdateView.as_view(), name='super_admin_client_edit'),
    path('super-admin/clients/<int:pk>/toggle-status/', super_admin.super_admin_toggle_client_status, name='super_admin_client_toggle_status'),
    path('super-admin/clients/<int:pk>/approve/', super_admin.super_admin_approve_client, name='super_admin_client_approve'),
    path('super-admin/clients/<int:pk>/reject/', super_admin.super_admin_reject_client, name='super_admin_client_reject'),
    path('super-admin/clients/<int:pk>/delete/', super_admin.super_admin_delete_client, name='super_admin_client_delete'),
    path('super-admin/clients/<int:pk>/extend/', super_admin.super_admin_extend_subscription, name='super_admin_client_extend'),
    path('super-admin/clients/<int:pk>/impersonate/', super_admin.super_admin_impersonate_client, name='super_admin_impersonate_client'),
    path('super-admin/clients/<int:pk>/reset-owner-password/', super_admin.super_admin_reset_owner_password, name='super_admin_reset_owner_password'),
    path('super-admin/clients/<int:business_pk>/payments/add/', super_admin.SuperAdminPaymentCreateView.as_view(), name='super_admin_payment_add'),
    path('super-admin/payments/', super_admin.SuperAdminPaymentListView.as_view(), name='super_admin_payment_list'),
    path('super-admin/users/', super_admin.SuperAdminUserListView.as_view(), name='super_admin_user_list'),
    path('super-admin/users/<int:pk>/delete/', super_admin.super_admin_delete_user, name='super_admin_user_delete'),
    path('super-admin/activity/', super_admin.SuperAdminActivityLogListView.as_view(), name='super_admin_activity_list'),
    path('super-admin/stop-impersonation/', super_admin.super_admin_stop_impersonation, name='super_admin_stop_impersonation'),
    path('business/', views.BusinessListView.as_view(), name='business_list'),
    path('business/add/', views.BusinessCreateView.as_view(), name='business_add'),
    path('business/<int:pk>/edit/', views.BusinessUpdateView.as_view(), name='business_edit'),
    path('business/<int:pk>/delete/', views.BusinessDeleteView.as_view(), name='business_delete'),
    path('clients/', views.ClientListView.as_view(), name='client_list'),
    path('clients/add/', views.ClientCreateView.as_view(), name='client_add'),
    path('suppliers/', views.SupplierListView.as_view(), name='supplier_list'),
    path('suppliers/statement/', views.SupplierStatementView.as_view(), name='supplier_statement'),
    path('suppliers/statement/pdf/', views.export_supplier_statement_pdf, name='export_supplier_statement_pdf'),
    path('clients/<int:pk>/statement/', views.ClientStatementView.as_view(), name='client_statement'),
    path('clients/<int:pk>/statement/pdf/', views.export_client_statement_pdf, name='export_client_statement_pdf'),
    path('clients/<int:pk>/edit/', views.ClientUpdateView.as_view(), name='client_edit'),
    path('clients/<int:pk>/delete/', views.ClientDeleteView.as_view(), name='client_delete'),
    path('transactions/', views.TransactionListView.as_view(), name='transaction_list'),
    path('transactions/add/', views.TransactionCreateView.as_view(), name='transaction_add'),
    path('transactions/<int:pk>/', views.TransactionDetailView.as_view(), name='transaction_detail'),
    path('transactions/<int:pk>/receipt/', views.TransactionReceiptView.as_view(), name='transaction_receipt'),
    path('transactions/<int:pk>/receipt/pdf/', views.export_transaction_receipt_pdf, name='transaction_receipt_pdf'),
    path('transactions/<int:pk>/invoice/', views.TransactionInvoiceView.as_view(), name='transaction_invoice'),
    path('transactions/<int:pk>/invoice/pdf/', views.export_transaction_invoice_pdf, name='transaction_invoice_pdf'),
    path('transactions/<int:pk>/edit/', views.TransactionUpdateView.as_view(), name='transaction_edit'),
    path('transactions/<int:pk>/delete/', views.TransactionDeleteView.as_view(), name='transaction_delete'),
    path('expenses/', views.ExpenseListView.as_view(), name='expense_list'),
    path('expenses/add/', views.ExpenseCreateView.as_view(), name='expense_add'),
    path('expenses/<int:pk>/edit/', views.ExpenseUpdateView.as_view(), name='expense_edit'),
    path('expenses/<int:pk>/delete/', views.ExpenseDeleteView.as_view(), name='expense_delete'),
    path('supply-expenses/', views.SupplyExpenseListView.as_view(), name='supply_expense_list'),
    path('supply-expenses/add/', views.SupplyExpenseCreateView.as_view(), name='supply_expense_add'),
    path('supply-expenses/<int:pk>/edit/', views.SupplyExpenseUpdateView.as_view(), name='supply_expense_edit'),
    path('supply-expenses/<int:pk>/delete/', views.SupplyExpenseDeleteView.as_view(), name='supply_expense_delete'),
    # reporting and backup
    path('reports/', ReportIndexView.as_view(), name='report_index'),
    path('reports/daily/', DailyReportView.as_view(), name='daily_report'),
    path('reports/monthly/', MonthlyReportView.as_view(), name='monthly_report'),
    path('reports/yearly/', YearlyReportView.as_view(), name='yearly_report'),
    path('reports/custom/', CustomReportView.as_view(), name='custom_report'),
    path('net-profit/', views.net_profit_detail, name='net_profit_detail'),
    path('daily-revenue-detail/', views.DailyRevenueDetailView.as_view(), name='daily_revenue_detail'),
    path('outstanding-balances/', views.OutstandingBalanceListView.as_view(), name='outstanding_balances'),
    path('supplier-outstanding-balances/', views.SupplierOutstandingBalanceListView.as_view(), name='supplier_outstanding_balances'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('team/', views.TeamManagementView.as_view(), name='team_management'),
    path('team/<int:pk>/edit/', views.TeamMemberUpdateView.as_view(), name='team_member_edit'),
    path('backup/', BackupView.as_view(), name='backup'),
    path('backup/download/', views.backup, name='backup_download'),
    path('restore/', RestoreView.as_view(), name='restore'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    # export functions
    path('export/daily/pdf/', export_daily_report_pdf, name='export_daily_report_pdf'),
    path('export/monthly/pdf/', export_monthly_report_pdf, name='export_monthly_report_pdf'),
    path('export/yearly/pdf/', export_yearly_report_pdf, name='export_yearly_report_pdf'),
    path('export/custom/pdf/', export_custom_report_pdf, name='export_custom_report_pdf'),
    # authentication
    path('login/', views.LoginView.as_view(), name='login'),
    path('account-inactive/', views.InactiveSubscriptionView.as_view(), name='inactive_subscription'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.LogoutView, name='logout'),
]
